### ISSUE TITLE
publish package

### ISSUE THREAD

**Issue by ryzokuken** [alex-kinokon/ical.ts#44]
Hi, I've ported my project to Deno but it doesn't yet have the ability to pull packages from GitHub repos. Could you publish it somewhere?

**Comment by alex-kinokon** [comment]
published as [tcal@0.1.0-beta.1](https://www.npmjs.com/package/tcal/v/0.1.0-beta.1)

**Comment by ryzokuken** [comment]
@alex-kinokon thanks a ton!
